### ISSUE TITLE
Allow to configure the node wrapper template

### ISSUE THREAD

**Issue by adamkleingit** [500tech/angular-tree-component#130]
Need to refactor the node component and extract small components / directives out of it (e.g. tree-node-expander, tree-node-mouse-actions, tree-node-children) - to allow overriding the external tree node template

**Comment by adamkleingit** [comment]
Fixed in 2.6.0

**Comment by adamkleingit** [comment]
Add template for wrapper

**Comment by adamkleingit** [comment]
#goodnessSquad

**Comment by DanielCaspers** [comment]
Hey @adamkleingit, Is there still a plan or intent to separate out `tree-node-expander` into a separate component as a part of this task as well? If not, I'm wondering if I should file this below under a new possible enhancement. Please let me know, and thanks for your hard work on the plugin!

------------


My use case would be to swap out the expander background image with a different icon library and then configure it from the template itself instead of overriding to remove the background-image caret and then inserting the new font by CSS3 'content' rule. 

Here would be one possible way it might look that would open up a lot of possibilities for users, using HTML projection.

`
<tree-node-expander>
      <i class='material-icons'>arrow_drop_down></i>
</tree-node-expander>
`

The projected content could then just go inside the current `.toggle-children-wrapper` element instead of the background image.
