### ISSUE TITLE
Firefox, page scrolls when selecting a node

### ISSUE THREAD

**Issue by adrian-mitangi** [500tech/angular-tree-component#183]
I'm noticing a real annoyance with the page scrolling down when a node is selected.  This is happening in firefox.  How can I disable this functionality?

**Comment by adrian-mitangi** [comment]
This behavior is happening on the demo site as well, https://angular2-tree.readme.io/.

**Comment by esugoi** [comment]
I am having this same behavior on Firefox. It seems to be working as expected on Chrome.

**Comment by adamkleingit** [comment]
Yes this is because I am using the renderer to invoke 'scrollIntoViewIfNeeded' - but that doesn't exist on firefox.
Need a polyfill - but the polyfill needs to use the renderer (otherwise we touch the DOM directly).

I think best would be to port an existing polyfill like:
https://github.com/stipsan/scroll-into-view-if-needed/blob/master/src/index.js

Anyone wants to make a PR?

**Comment by esugoi** [comment]
I see...
I tried to import this polyfill for the webkit method:
https://www.npmjs.com/package/element.scrollintoviewifneeded-polyfill

It seems to be working as expected until now.

**Comment by adamkleingit** [comment]
This should be solved in the latest version after moving to virtual scroll

**Comment by adrian-mitangi** [comment]
Thanks @adamkleingit,

I'll try it out this week.
