### ISSUE TITLE
Programatically fire click event on tree node

### ISSUE THREAD

**Issue by dangeabunea** [500tech/angular-tree-component#333]
Hi,

Is it possible to fire the selected (click) event programmatically on a TreeNode? I noticed that there is a fireEvent method but I could not find any example of how to use it.

let node = this.tree.treeModel.getFirstRoot();
this.tree.treeModel.setFocusedNode(node);
node.fireEvent('???')  // how to click this node programatically?

Thank you so much

**Comment by PrajwalGonsalves07** [comment]
+1

**Comment by adamkleingit** [comment]
@dangeabunea, let me understand - you want to focus on the first root, but fire the selected event?
Why not activate the first root instead of just focusing on it?

Also, the purpose of an event is to let you know that something happened in the tree. If you are the one who initiates the action you can act upon it yourself.

Finally, if you really want to fire an event, just look at the code inside tree.model.ts. It's something like:
`treeModel.fireEvent({ eventName: TREE_EVENTS.onActivate, node })`

**Comment by aipirvu** [comment]
> Also, the purpose of an event is to let you know that something happened in the tree. If you are the one who initiates the action you can act upon it yourself.

@adamkleingit True but your code would be more coupled. Instead of having a method changing the active node and a handler to react to the node change you will need to manually call your handle logic from your other method.
