### ISSUE TITLE
ACE Admin theme not working properly

### ISSUE THREAD

**Issue by karangarg45** [500tech/angular-tree-component#407]
Hi,

I am not getting the proper output as show in screenshot
https://files.readme.io/0bd50e1-treecss.png
Has there been any changes?

**Comment by MintL** [comment]
I found that changing *treenode* to *tree-node* and *treenodeexpander* to *tree-node-expander* in the CSS it worked better. Dunno if this has been changed recently.

**Comment by GlebBigma** [comment]
Guys, where is the html example for ACE Admin theme?

**Comment by crivadavi** [comment]
This is the [link](https://angular2-tree.readme.io/docs/styling), the example is the last

**Comment by crivadavi** [comment]
Using ACE Admin theme on a tree with more than 2 levels, the dotted lines don't stop where they should. This is because of setting the border-left on tree-children::before, in fact it contains the second level childs, so the border doesn't stop at the grandchild, but continue for all the great grandchild
See the picture where, the wrong line is crossed in red. 

<img src="http://i67.tinypic.com/2czynwy.png"/>

There is someone that has solved this style problem?

**Comment by adamkleingit** [comment]
Hi,
example themes are provided by the community. If anyone wishes to fix it I
will gladly update the docs


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by jaiparkashyadav** [comment]
Can anyone please share more details about implementing the Ace Admin theme. Like HTML,  .ts and .scss files or may be stepings.

Regards,
Jai

**Comment by dmaheshwarareddy** [comment]
Hi ,

I have tried to use this theme in angular however still it is not working.

Thanks,
Mahesh

**Comment by Divyashree92** [comment]
Has anybody solved the above issue?

**Comment by meenakshikp03** [comment]
Is this issue resolved? ACE Admin theme is not giving the expected result.
