### ISSUE TITLE
Include unmatched children in matched parents during filtering

### ISSUE THREAD

**Issue by ronnyek** [500tech/angular-tree-component#412]
https://www.webpackbin.com/bins/-Kstxzqmi2M4-h3QbgeS

Apologies for the horrible title... I dont know how else to put this. If you were to expand all nodes in the included above example, and then searched for child2.2 and hit filter, it does indeed find that node, but hides all this nodes children. 

What I'd ultimately like to achieve would be to have search end its recursion once it hit a match.  (in this case including the node called uniquechild). 

I understand that the search functionality only takes us so far, and beyond that, we're responsible for showing and hiding nodes ourselves. My problem is I can think of any efficient way of accommodating this. Recursive function effectively checking a parent and when navigating a matched entry explicitly set all to show, or all to false.  I would think this functionality would actually be more common for what people actually want out of a filter.

appreciate any pointers here

**Comment by adamkleingit** [comment]
Hi,
The mechanisms the tree offers for custom filtering are:
- calling `filterNodes` and pass it a custom function to filter by.
- going over the nodes recursively and call `setIsHidden` / `show` / `hide`.

If you happen to implement the above behaviour I would love to include it in the readme page as an example, because it might be useful for other developers as well.

BTW, it sounds like what you're trying to achieve is more of a search than a filter - which is currently not part of the tree but can be implemented on top of it (with scrollIntoView and the methods you have for traversing the tree).

Hope it helps
