### ISSUE TITLE
SystemJS: Does this really not work?

### ISSUE THREAD

**Issue by markkesty** [500tech/angular-tree-component#417]
I've noticed that you explicitly claim that your component doesn't work with SystemJS. However, there are many references to SystemJS both in your documentation and on stackoverflow.

It's working in the following plunker: https://embed.plnkr.co/zLIs2Q4uMqGgastSOKJG/

If it's working here, can I assume that it really does work with SystemJS and your documentation is outdated or am I missing something and will encounter trouble down the road?

**Comment by DavidKDeutsch** [comment]
I have a related question, though it is admittedly not 100% specific to the angular-tree-component: in what way is the component not compatible with SystemJS? My understanding is that SystemJS can consume a variety of different module formats, so in _theory_ a component doesn't have to do anything special to be compatible with SystemJS.

A little background: I'm relatively new to Angular 2+, AOT, JSPM, etc., and am working on upgrading an existing angular.js app using the ngUpgrade module. This is a "portal" type app, which loads widgets on-demand at runtime from arbitrary URLs (based on a config), whereas all Angular examples I see know about their components a build time. I've been using SystemJS instead of Webpack, as the former allows me to bundle code into a file while still allowing the dynamically loaded components to access the modules registered within that bundle. While I have been able to bundle the main app just fine via JSPM, I have run into a variety of issues trying to dynamically load widgets bundled with JSPM, as well as compiling the widgets using AOT, etc. If anyone knows of an example of this kind of scenario they could point me to, it would be much appreciated.

I apologize again for the fact that this question doesn't really have much to do with angular-tree-component, but it turns out that one of our widgets is/was planning to use that component, so I was hoping that the developers here could shed some light on the challenges associated with SystemJS/JSPM.

**Comment by DavidKDeutsch** [comment]
@markkesty - to answer your question, I believe it works up to version 3.4.0 of the tree component; your plunker is using 3.2.3, which is probably why it works.

@adamkleingit - any insight you may have as far as my question above? I'm trying to determine what it is _about_ SystemJS that causes issues, since it would seem that unless there is something especially "weird" about the tree component, there must be a bug in SystemJS.

**Comment by omarpando** [comment]
@adamkleingit - In the company I work for we have a similar situation to @DavidKDeutsch 's, please if you have the time to give us some insight that will be very helpful. Thank you very much for this great component.

**Comment by adamkleingit** [comment]
@omarpando , @DavidKDeutsch @markkesty 
In order to support SystemJS, I need to compile a .umd version, and make sure all dependencies are included inside, or rely on the user to provide it.
We decided to stop supporting it because:
a. It came to a situation where half of the bugs are SystemJS related
b. The industry is moving towards Webpack

I believe you can still make it work with version 5.0.0 as well but I am not supporting it

Hope it makes sense
