### ISSUE TITLE
ERROR TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by ankita199** [500tech/angular-tree-component#449]
Hi,

I am trying to add Search functionality in my tree node.

Added this line in html
<input #filter (keyup)="tree.treeModel.filterNodes(filter.value)" placeholder="filter nodes" />

in my ts
@ViewChild(TreeComponent) treeComponent: TreeComponent;

When i am trying to search in input it throws "ERROR TypeError: Cannot read property 'emit' of undefined".

i am using "angular-tree-component": "4.0.0" version. Can anyone help me with issue?

**Comment by jlouiss** [comment]
You could do something like this
```
<input #filter (keyup)="tree.treeModel.filterNodes(filter.value)" placeholder="filter nodes">
<tree-root #tree [nodes]="nodes"></tree-root>
```
I think you don't need any ViewChild in this case

**Comment by adamkleingit** [comment]
@ankita199 looks like you are referencing `tree` but the viewChild name is `treeComponent`

**Comment by Luis16287** [comment]
Same issue, same angular-tree-component version (4.0.0)

In my html
` <input #filter (keyup)="filterNodes(filter.value)" placeholder="Filtrar tareas..."/>`
`<tree-root class="scrollbar-style-1"
      #tree
      [nodes]="nodes"
      [options]="customTemplateStringOptions"
      [focused]="true"
      (event)="onEvent($event)"
      (initialized)="onInitialized(tree)"
    >`

In my ts
`@ViewChild` ('tree') tree: `TreeComponent;`

I use `@ViewChild `because in a modal I add a new task and update `nodes `and after doing this I need to use `this.tree.treeModel.update();` 
`this.tree.sizeChanged();` 

When i am trying to search in input it throws `"ERROR TypeError: Cannot read property 'emit' of undefined".`

**Comment by ankita199** [comment]
It is still the issue..
