### ISSUE TITLE
Demo: Docs examples are not loading

### ISSUE THREAD

**Issue by henev** [500tech/angular-tree-component#528]
On [docs page](https://angular2-tree.readme.io/docs), demos are not laoding.

Using latest Chrome.

Shows _**Loading...**_ in the demo box but nothing happens and there is error in the console:

![screenshot from 2018-01-08 15-59-19](https://user-images.githubusercontent.com/6638268/34669811-f9367d92-f48c-11e7-87b4-5e299ac615dc.png)

**Comment by mpGitHub** [comment]
I am unable to find a working demo of this library in the demo docs linked on this site or in any jsFiddle / plunker examples. Is this repo being abandoned or the demo docs just not updated?

**Comment by sarora2073** [comment]
Experienced the same issue in Chrome. Turns out that there's a security issue that can be worked around by lowering security level on the browser e.g. as detailed [here](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document)

On a related note -- i'm hoping this security-level doesn't have to be lowered for anyone using this package, as many users block 3rd party cookies. Does anyone know if there's a general problem with the package, or is it just an issue with the docs site?

**Comment by adamkleingit** [comment]
Just checked - it's just in the docs site.
Go here to see:
https://rawgit.com/500tech/angular-tree-component/master/example/cli/dist/#/basic
