### ISSUE TITLE
How to set IsSelected nodes by default?

### ISSUE THREAD

**Issue by DMITRYTISHKIN** [500tech/angular-tree-component#553]
How to set IsSelected nodes by default?

**Comment by gvillafanetapia** [comment]
You are supposed to be able to select them by setting the property isSelected to true in the node. But it doesn't seem to be working.

**Comment by brampeirs** [comment]
I do it like this and it seems to work:
node.**set**IsSelected(true);

**Comment by gvillafanetapia** [comment]
Yes, with the method setIsSelected it works.

**Comment by Marfyy** [comment]
I'm not exactly sure what OP means by selected "by default", but my scenario is that I want to mark nodes as **selected at startup, when I initialize the [nodes] directive**. I use a checkbox tree. It might be what @DMITRYTISHKIN wants aswell.

Reading from the [docs](https://angular2-tree.readme.io/docs/options-1), you are able to set a node as expanded on startup. I would love the same functionality for active/selected.

The problem I ran into was that I have a data structure that specifies the tree structure, and it also specifies if a node should be selected (checkbox ticked) or not.

If I load the nodes via directive, and immediately look for the nodes via "treeModel.getNodeById()" I get an exception. You can get around this by delaying the setIsSelected by a setTimeout. 
This behavior makes sense, because of the angular lifecycle. The data in the directive has to go through the OnChanges routine before they can be manipulated. Delaying it a cycle makes it work.

Here is a plunkr that shows the problem. Its a working workaround, but not the cleanest solution. 
[https://plnkr.co/edit/cMUwDa7lO8OtbDUtksKo?p=preview](https://plnkr.co/edit/cMUwDa7lO8OtbDUtksKo?p=preview)

The dream scenario would be something like this:
`const NODES = [
  {
    id:'1', 
    name:'Root', 
    children: [
      {
        id:'2',
        name:'First Child',
        isSelected: true
      },
      {
        id:'3',
        name:'Second Child',
        isSelected: true
      }
    ]
  }
]`

I'm thinking that the normal logic of selecting a parent also selects the children should apply. However it should be configurable of this select emits the select action event.

I've been trying see if I can contribute with a solution myself, but sitting in a windows environment, the build scripts aren't cooperating with me yet :)

**Comment by adamkleingit** [comment]
Setting isSelected in advance will not be supported in future versions. We are keeping tree state apart from tree data.
You have 2 options:
1) As mentioned above and described here: https://angular2-tree.readme.io/docs/expanding-all-on-init
2) By binding to tree state: https://angular2-tree.readme.io/docs/save-restore

**Comment by jsight** [comment]
It seems to me that setting the selectedNodeIds in the state only works for nodes that are already visible?

**Comment by jsight** [comment]
Oh, never mind, it was me misunderstanding the API.

**Comment by larisaVasile** [comment]
@ViewChild('tree') treeComponent: TreeComponent;  
onCheckAllButtonClick() {
   const treeModel: TreeModel = this.treeComponent.treeModel;
   const nodes = treeModel.nodes;
   for (const node of nodes) {
     for (const child of node.children) {
       treeModel.getNodeById(child.id).setIsSelected(true);
     }
   }
  }
