### ISSUE TITLE
isExpanded doesn't seem to be working

### ISSUE THREAD

**Issue by ndw** [500tech/angular-tree-component#98]
I'm using 1.3.5 on Angular 2.1.0. 

````
{id: 55, name: "Recipes (…)", children: Array[2], expanded: true}
````

Neither setting isExpanded nor explicitly setting isExpandedField to something else ("expanded" as shown above) seems to have any effect on the display.

**Comment by chriswestgaard** [comment]
I have the same problem. Have tried both expanded: true and isExpanded: true.

**Comment by Shadowlauch** [comment]
I have the same problem. There is a workaround though. The expanded Node Ids are saved in the tree model and if you update that object after you updated your data it will expand the tree.

You need to access the treeModel and its property "expandedNodeIds", this is an Object that uses the IDs of the nodes as the key and the value represents the state of the node (true: expanded, false: not expanded). Be carefull though this does not takae into effect parents and if you expand a node that doesn't have children you will get a permanent "loading" message. This is obviously a bit more work.

**Comment by adamkleingit** [comment]
Hi,
are you talking about children that are being loaded asynchronously? If so it's a known problem that I intend to solve soon.

**Comment by ndw** [comment]
Not in my case.

**Comment by adamkleingit** [comment]
Can you send code example / the nodes + options you are passing in?

I just want to state that 'isExpanded' only works if it's on the nodes initially when you pass them to the tree.
The Tree does not listen to changes in the data, so if you want to expand the nodes at some point you should use the API to locate the node (by id, path or something else) - and then call the `expand()` method.

**Comment by denkomanceski** [comment]
@adamkleingit I was thinking about opening an issue on this as well, but than I saw your previous comment: Will it be possible to add isExpanded flag to children that are loaded asynchronously ? And another question would be: can I access the tree model directly to actually preserve the state of the tree when switching between routes/tabbed content ? I plan to add isExpanded = true directly to the model AFTER the user expands that leaf, and keep the tree model in a service, so next time the tree is recreated, it should be the same as before

**Comment by adamkleingit** [comment]
Hi,

1.
version 2.4.0 fixes isExpanded on async children. Notice that this version has some breaking changes.

2.
I'm trying to avoid changing the data that the user supplies, so I hold the expanded nodes IDs / selected node IDs in a separate list.

That's why I don't like the `isExpanded` feature so much, as it creates some duplication and confusion.

3.
I intend to add 'getState()' and 'setState()' methods to the tree so you can save / restore them whenever you like.

Until then - you can hack it by getting and setting `expandedNodeIds`, `activeNodeIds` and `focusedNodeId`, then calling treeModel._calculateExpandedNodes();
But notice that this is not a public API and might change in future versions.

**Comment by denkomanceski** [comment]
@adamkleingit Thanks for the suggestion but the getState alternative (with _calculateExpandedNodes()) does not seem to work. I think this is because the nodes are loaded asynchronously and it doesnt know which are these expandedNodesIds because they do not exist yet. Am I right? Here is a screenshot: http://prntscr.com/deirog. What I did is when the component which has the tree is destroyed (ngOnDestroy) I am saving the state, and than when the tree is initialized again (onInitialized) I am doing what you told me to do (setting the nodes and calling calculateExpandedNodes). Do you know how can I make this work properly ?
